# Generated by Django 3.1.2 on 2020-10-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201030_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='sub_category_photo',
            field=models.ImageField(null=True, upload_to='sub_category/'),
        ),
    ]
