# Generated by Django 3.1.2 on 2020-10-30 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201030_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='sub_category_name',
            new_name='subcategory_name',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='sub_category_photo',
            new_name='subcategory_photo',
        ),
    ]
